// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD0AG7RNG0Fm2GDZR1555gVI1-A8tBAFS0',
    appId: '1:615525483494:web:fdb7566adcace07e234c27',
    messagingSenderId: '615525483494',
    projectId: 'universities-2b803',
    authDomain: 'universities-2b803.firebaseapp.com',
    storageBucket: 'universities-2b803.appspot.com',
    measurementId: 'G-GHSVZCGF7D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDlEGQCxOb_REk3OvCw-Z_chCBVNBcGNtY',
    appId: '1:615525483494:android:8a438516ccd803d8234c27',
    messagingSenderId: '615525483494',
    projectId: 'universities-2b803',
    storageBucket: 'universities-2b803.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDQo4G6UdBF9kNRq2_09nzGogI-Q8pfdD8',
    appId: '1:615525483494:ios:117ac5ba5647a94d234c27',
    messagingSenderId: '615525483494',
    projectId: 'universities-2b803',
    storageBucket: 'universities-2b803.appspot.com',
    iosClientId: '615525483494-bapopolojg2b9d6sklgpjnh3qkqsid67.apps.googleusercontent.com',
    iosBundleId: 'com.example.universities',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDQo4G6UdBF9kNRq2_09nzGogI-Q8pfdD8',
    appId: '1:615525483494:ios:117ac5ba5647a94d234c27',
    messagingSenderId: '615525483494',
    projectId: 'universities-2b803',
    storageBucket: 'universities-2b803.appspot.com',
    iosClientId: '615525483494-bapopolojg2b9d6sklgpjnh3qkqsid67.apps.googleusercontent.com',
    iosBundleId: 'com.example.universities',
  );
}
